# docker-compose.yml
version: '3'
services:
    backend:
        build: .
        container_name: flask
        hostname: flask
        restart: always
        command: gunicorn -b 0.0.0.0:7000 app:app --reload -w 2 --threads 2
        ports:
            - "7000:7000"
        networks:
            - default
    frontend:
        build: ./nginx
        hostname: nginx
        container_name: nginx
        restart: always
        ports:
            - "80:80"
        networks:
            - default
        depends_on:
            - backend
    postgres:
        image: postgres:10
        environment:
            - POSTGRES_DB=developer
            - POSTGRES_USER=developer
            - POSTGRES_PASSWORD=devpassword
        volumes:
            - postgres-data:/var/lib/postgresql/data
        ports:
            - "127.0.0.1:25000:5432"
    redis:
        image: redis:latest
        ports:
            - "127.0.0.1:25100:6379"
        command: redis-server --save ""

volumes:
    postgres-data:
        driver: local