"""init

Revision ID: 2b6c3d9ffa8c
Revises: ec3b07ceb21f
Create Date: 2023-03-31 16:52:26.612967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b6c3d9ffa8c'
down_revision = 'ec3b07ceb21f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
