"""please

Revision ID: 91318b9d2197
Revises: 2b6c3d9ffa8c
Create Date: 2023-03-31 16:54:37.901456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91318b9d2197'
down_revision = '2b6c3d9ffa8c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
